### ISSUE TITLE
Generated pdf doesn't support utf8 languages

### ISSUE THREAD

**Issue by abozanona** [weDevsOfficial/weforms#153]
When I try to export a report that has Arabic words, the words letters doesn't align in the correct order.
![image](https://user-images.githubusercontent.com/12738028/55683458-ce968880-5948-11e9-852e-355ef2d2f079.png)

**Comment by mahbubme** [comment]
Hello @abozanona,

We are using Dompdf library to generate pdf, but we just noticed that the library does not support CSS direction which is required to fix the issue. For this reason, we are thinking to use another library. Hopefully, you will get it fixed in the future releases.

Dompdf reference: https://github.com/dompdf/dompdf/wiki/CSSCompatibility

Thanks for your understanding.

**Comment by mahbubme** [comment]
Fixed in the pro version
