### ISSUE TITLE
Enhancement: Coding issue

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/weforms#183]
This is more like an enhancement request. 

**Description of the requested enhancement:**

There is a missing line in our WP-content/plugins/weForms/includes/class-frontend-form.php, line number 35. The line  `weforms()->scripts->enqueue_frontend();` is available. But the line: `weforms()->scripts->register_frontend();`  is missing. This seems to create conflict between weForms and lightbox. So adding the line fixes the issue. 

**How to Reproduce:**
When lightbox is used with weForms to show the forms in popup, the form is not rendered properly, especially the style. 

**Evidence**:
A screenshot of the missing line is [here](https://prnt.sc/qhdlja).

**Current Behaviour**:
Since the line in the screenshot is unavailable within weForms, the style of the form is unavailable when the forms are used with lightbox to pop up. 

**Expected Behaviour**:
Adding the line 
`weforms()->scripts->register_frontend(); `
 fixes the issue. So, it requires developers' attention.

**Comment by different-thinking** [comment]
Hello,
I'm the person who raised that issue. I think this is not an enhancement request. I have several problems using weforms. From my theme devolpers (ThriveThemes) I got the following feedback on that issue:

"Our developers investigated the issue and it seems that the issue was here with the plugin itself.

The plugin code is poorly written.

There was an instance where the front-end scripts were en-queued but not registered.
https://share.getcloudapp.com/6quLeWDJ."

Please get me right: Thats no offense - I just want to get this solved.

Using weforms here: https://preprod.servicemanagement.tools/4me-hersteller-von-service-management-tools/ styling & conditional logic is working (click on "Klicken Sie hier für Kontaktaufnahme")
Using weforms here: https://preprod.servicemanagement.tools/agabu-ist-nonsens-oder-warum-standards-best-practices-doch-sinnvoll-sind/ (click on "direkt Kontakt aufnehmen") Style is nearly as it should be - conditional logic is not working

I assume there is some refactoring necessary.

Best
Robert
